Develop
luntungle/adidas-shop-frontend pull request #1
Opened 2017-05-18 09:02 UTC by luntungle

2017-05-19 09:46 UTC, imevro requested changes
Фикси

2017-05-19 09:46 UTC, evgenyrodionov commented on .gitconfig
> +[user]
Убери это отсюда

2017-05-19 09:46 UTC, evgenyrodionov commented on .ssh/id_rsa
> +-----BEGIN RSA PRIVATE KEY-----
Светанула свой ссш-ключ, убирай отсюда и перегенерируй

2017-05-19 09:46 UTC, evgenyrodionov commented on src/App.jsx
> +  {''/* min-height: 100vh;
Да чисти комментарии, я тебе уже в десятый раз говорю

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/Header/ColorSelector.jsx
> +{''/* top: 4px;
Опять мусор

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/Header/ColorSelector.jsx
> +display: flex;
Что с отступами

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/Header/HeaderRight2.jsx
> +top: 30px;
Отступы

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/Header/HeaderRight2.jsx
> +  {''/* position: absolute; */}
Мусор

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/Header/HeaderRight2.jsx
> +position: relative;
Пляска из отступов

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/Details/index.jsx
> +  margin-left: 80px;
Нет, верни как было

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +// const CardLabel = styled(Label)`
Мусор

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Sidebar/Logo/index.jsx
> +  <Img href="http://www.adidas.com">
Почему у тебя компонент ведёт себя как ссылка, но называется IMG?

И тут реакт-роутеровский Линк должен быть и вести на главную страницу /, а не на адидас.ком

2017-05-19 09:46 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import img from './dropdownicon.svg';
img → dropdownIcon

2017-05-19 09:46 UTC, evgenyrodionov commented on src/components/Label.jsx
> +  position: ${props => (props.isList ? 'absolute' : 'static')};
Нет, порочная практика https://github.com/disha1010/sport-store/pull/7#discussion_r117441297

Переделывай

2017-05-19 09:46 UTC, evgenyrodionov commented on src/components/Label.jsx
> +export default PinkSale;
PinkSale? Что с названием?

2017-05-22 09:02 UTC, luntungle commented on src/Products/Details/Header/HeaderRight2.jsx
> +top: 30px;
весь этот файл - мусор, остался как вариант, удаляю

2017-05-23 10:35 UTC, imevro requested changes

2017-05-23 10:35 UTC, imevro commented on .gitignore
> +.ssh
Ссш вообще не должно быть в репозитории, убирай саму директорию, а не в гитигнор засовывай. Это мусор

2017-05-23 10:35 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import dropdownicon from './dropdownicon.svg';
dropdownIcon from './dropdown-icon.svg'

2017-05-23 10:35 UTC, evgenyrodionov commented on src/Sidebar/Search/index.jsx
> +import searchicon from './searchicon.svg';
Как и выше

2017-05-23 14:11 UTC, merged